# Generated by Django 4.2.7 on 2023-12-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pose', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='felt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=200)),
                ('location', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='horrible',
        ),
    ]
