# Generated by Django 5.0 on 2024-02-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pose', '0002_felt_delete_horrible'),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=122)),
                ('salary', models.CharField(default=True, max_length=12)),
            ],
        ),
    ]
